name: Build and Run Dockerfile

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            miabrooker1/shift-automation:latest
          cache-from: type=registry,ref=miabrooker1/shift-automation:latest
          cache-to: type=registry,ref=miabrooker1/shift-automation:latest,mode=max

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull Docker image
        run: docker pull miabrooker1/shift-automation:latest

      - name: Run Docker container
        run: |
          docker run --rm miabrooker1/shift-automation:latest --headless
