name: Build, cache, and update Dockerhub:latest

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t miabrooker1/shift-automation:latest -f ./app/Dockerfile.windows .

      - name: Push Docker image to DockerHub
        run: docker push miabrooker1/shift-automation:latest

  run:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull miabrooker1/shift-automation:latest

      - name: Run Docker container
        run: |
          docker run --rm miabrooker1/shift-automation:latest --headless
