name: Build, cache, and update Dockerhub:latest

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull cache image
        run: docker pull miabrooker1/shift-automation:cache || exit 0

      - name: Build Docker image with cache
        run: |
          docker build \
          --cache-from=miabrooker1/shift-automation:windows-cache \
          --tag miabrooker1/shift-automation:windows-latest \
          --file ./app/Dockerfile.windows \
          .

      - name: Tag cache image
        run: docker tag miabrooker1/shift-automation:windows-latest miabrooker1/shift-automation:windows-cache

      - name: Push cache image to DockerHub
        run: docker push miabrooker1/shift-automation:windows-cache
